// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Es una obra literaria de mucha importancia a nivel nacional e internacional, ya que por décadas fue utilizado por muchas personas con la maravillosa labor de enseñar, más que todo a los niños en el increíble camino de la lectura y escritura.",
                            ImageUrl = "https://resources.diariolibre.com/images/2022/09/29/9789945125030-es-20db2495-focus-0.17-0.59-895-573.jpg",
                            Price = 9.99m,
                            Title = "Nacho"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Es una novela de la escritora chilena Isabel Allende, publicada en el año 2009, que cuenta la historia de una esclava llamada Zarité en el Haití del siglo XVIII. Acerca de su protagonista, Allende ha declarado: «De todos los personajes que he creado, el de Zarité es para mí el que más tengo la sensación de que existió.",
                            ImageUrl = "https://quelibroleo.com/images/libros/libro_1363451479.jpg",
                            Price = 7.99m,
                            Title = "Isla bajo el mar"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Deja en evidencia el problema de fondo del narcotráfico en México: la complicidad del Estado. Con testimonios claves de Vicente Zambada Niebla, la autora indaga en el perfil y la historia de su padre Ismael, el Mayo, el cabecilla más importante del Cártel de Sinaloa.",
                            ImageUrl = "https://m.media-amazon.com/images/I/41gTtABndrL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
                            Price = 6.99m,
                            Title = "El traidor"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorEcommerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
